

AliAnalysisGrid* CreateAlienHandler(Int_t runNumber = 126007, TString dataSet = "LHC10d", TString pass = "pass2", TString gridMode = "test", Bool_t kUseMC = kTRUE, TString rootVer = "v5-34-08", TString alirootVer = "v5-05-35-AN", Bool_t mergeJDL = kFALSE, TString workDir = "")
{
  // Check if user has a valid token, otherwise make one. This has limitations.
  // One can always follow the standard procedure of calling alien-token-init then
  //   source /tmp/gclient_env_$UID in the current shell.
  //   if (!AliAnalysisGrid::CreateToken()) return NULL;
  AliAnalysisAlien *plugin = new AliAnalysisAlien();
  plugin->SetOverwriteMode();
  // Set the run mode (can be "full", "test", "offline", "submit" or "terminate")
  plugin->SetRunMode(gridMode.Data());
  plugin->SetMergeViaJDL(mergeJDL);
  plugin->SetOneStageMerging(kFALSE);
  plugin->SetMaxMergeStages(3);
  // Set versions of used packages
  plugin->SetAPIVersion("V1.1x");
  plugin->SetROOTVersion(rootVer.Data());
  plugin->SetAliROOTVersion(alirootVer.Data());
  plugin->SetUseSubmitPolicy();
  // Declare input data to be processed.
  // Method 1: Create automatically XML collections using alien 'find' command.
  // Define production directory LFN
  // On real reconstructed data:

  if(kUseMC)
    {
      plugin->SetGridDataDir(Form("/alice/sim/2011/%s", dataSet.Data()));
      plugin->SetDataPattern("*AliESDs.root");
    }
  else
    {
      plugin->SetGridDataDir(Form("/alice/data/2010/%s", dataSet.Data()));
      if(dataSet.EndsWith("c"))
	{
	  plugin->SetDataPattern(Form("*ESDs/%s_7tev/*AliESDs.root", pass.Data()));
	}
      else
	plugin->SetDataPattern(Form("*ESDs/%s/*AliESDs.root", pass.Data()));
    }

  if(!kUseMC)
    plugin->SetRunPrefix("000");   // real data
  // ...then add run numbers to be considered
  plugin->AddRunNumber(runNumber);
  //plugin->SetOutputSingleFolder("output");
  plugin->SetOutputToRunNo();

  if(kUseMC)
    {
      workDir += "/MC";
    }
  else
    {
      workDir += "/data";
    }
  
  workDir += Form("/%s.%s", dataSet.Data(), pass.Data());

  plugin->SetGridWorkingDir(workDir.Data());
  plugin->SetAnalysisSource("*.cxx"); //Your analysis task
  // Declare all libraries (other than the default ones for the framework. These will be
  // loaded by the generated analysis macro. Add all extra files (task .cxx/.h) here.
  /*
    //if needed load external packages
    plugin->AddExternalPackage("boost::v1_43_0");
    plugin->AddExternalPackage("cgal::v3.6");
    plugin->AddExternalPackage("fastjet::v2.4.2");
  */

  //here you have to load all the additional libraries to the 'core' ones
  //and all the files you will be working with, which are not in the official framework along with your tasks and macros needed to add the task to your running macro
  plugin->SetAdditionalLibs("libPWGmuon.so libPWGTools.so AddTask*.C AliAnalysisTask*.cxx AliAnalysisTask*.h");
  plugin->SetDefaultOutputs();
  //all the files you do not wish to merge
  plugin->SetMergeExcludes("AliAOD.root pyxsec_hists.root");
  //here you can set the names of the macros generated by the alienplugin
  plugin->SetAnalysisMacro("*.C");
  plugin->SetExecutable("*.sh");
  plugin->SetJDLName("*.jdl");
  plugin->SetTTL(15000);
  // Optionally set input format (default xml-single)
  plugin->SetInputFormat("xml-single");
  // Optionally modify the name of the generated JDL (default analysis.jdl)
  // Optionally modify job price (default 1)
  plugin->SetPrice(1);      
  // Optionally modify split mode (default 'se')    
  plugin->SetSplitMode("se");
  //This exits alien shell once the jobs are submitted
  plugin->SetDropToShell(kFALSE);
  return plugin;
}
